version: '3.3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    container_name: foodgram_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    container_name: foodgram_backend
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/backend_media
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: foodgram_frontend
    build:
      context: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    container_name: foodgram_gateway
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/gateway_static
      - media:/gateway_media
      - docs:/docs