# Generated by Django 4.2 on 2024-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
