# Generated by Django 4.2 on 2024-02-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_shoppinglist_ingredient_amounts'),
        ('users', '0003_alter_customuser_favorite_recipes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
