# Generated by Django 4.2 on 2024-02-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_unitkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.unitkind', verbose_name='Вид единицы измерения'),
            preserve_default=False,
        ),
    ]
