# Generated by Django 4.2 on 2024-02-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_delete_shoppinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количества ингредиентов'},
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='г', max_length=10, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitKind',
        ),
    ]
