# Generated by Django 4.2 on 2024-02-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientamount_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_to_cook',
            new_name='cooking_time',
        ),
    ]
