# Generated by Django 4.2 on 2024-02-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(to='recipes.recipe', verbose_name='Избранное'),
        ),
    ]
