# Generated by Django 4.2 on 2024-02-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientamount_ingredient'),
        ('users', '0002_alter_customuser_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favoriters', to='recipes.recipe', verbose_name='Избранное'),
        ),
    ]
