# Generated by Django 4.2 on 2024-02-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_shoppinglist_ingredient_amounts'),
        ('users', '0002_alter_customuser_favorite_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe', verbose_name='Избранное'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shopping_list',
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='shoppers', to='recipes.ingredientamount', verbose_name='Список покупок'),
        ),
    ]
