# Generated by Django 4.2 on 2024-02-21 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_favorite_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
